In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
hateCrimeBias = pd.read_csv("Hate_Crime_Incidents_per_Bias_Motivation_and_Quarter_by_State_Federal_and_Agency_2019.csv")
hateCrimeBias.head()

,State,Agency Type,Agency,Race/\nEthnicity/\nAncestry,Religion,Sexual\norientation,Disability,Gender,Gender\nidentity,1st\nquarter,2nd\nquarter,3rd\nquarter,4th\nquarter,Population
0,Alaska,Cities,Anchorage,4.0,0,2.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,"287,731"
1,Alaska,Cities,Fairbanks,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"31,493"
2,Alaska,Cities,Kotzebue,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,"3,272"
3,Alaska,Cities,North Pole,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,"2,111"
4,Alaska,Cities,Soldotna,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,"4,756"

In [3]:
print(hateCrimeBias.shape)
print(hateCrimeBias.columns)

(2175, 14)
Index(['State', 'Agency Type', 'Agency', 'Race/\nEthnicity/\nAncestry',
       'Religion', 'Sexual\norientation', 'Disability', 'Gender',
       'Gender\nidentity', '1st\nquarter', '2nd\nquarter', '3rd\nquarter',
       '4th\nquarter', 'Population'],
      dtype='object')

In [4]:
counts = hateCrimeBias.nunique()
counts

State                            51
Agency Type                      11
Agency                         1902
Race/\nEthnicity/\nAncestry      33
Religion                         21
Sexual\norientation              22
Disability                        7
Gender                            5
Gender\nidentity                  9
1st\nquarter                     21
2nd\nquarter                     23
3rd\nquarter                     24
4th\nquarter                     20
Population                     1595
dtype: int64

In [7]:
hateCrimeBias['State'].value_counts().head()

New Jersey    209
California    195
Michigan      188
Texas         167
Ohio          134
Name: State, dtype: int64

In [23]:
hateCrimeBias.isna().sum()

State                            8
Agency Type                      2
Agency                           2
Race/\nEthnicity/\nAncestry      3
Religion                         2
Sexual\norientation              3
Disability                       3
Gender                           3
Gender\nidentity                 3
1st\nquarter                    73
2nd\nquarter                    49
3rd\nquarter                    73
4th\nquarter                    89
Population                     567
dtype: int64

In [3]:
nyc = pd.read_csv("Resources/New_York_Hate_Crimes_by_County_and_Bias_Type_2010-2019.csv")
nyc

,County,Year,Crime Type,Anti-Male,Anti-Female,Anti-Transgender,Anti-Gender Identity Expression,Anti-Age*,Anti-White,Anti-Black,...,Anti-Gay Male,Anti-Gay Female,Anti-Gay (Male and Female),Anti-Heterosexual,Anti-Bisexual,Anti-Physical Disability,Anti-Mental Disability,Total Incidents,Total Victims,Total Offenders
0,Albany,2010,Crimes Against Persons,0,0,0,0,0,0,9,...,2,1,0,0,0,0,0,13,13,20
1,Albany,2010,Property Crimes,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,2,2,2
2,Albany,2011,Crimes Against Persons,0,0,0,0,0,0,4,...,2,0,0,0,0,0,0,7,7,7
3,Albany,2011,Property Crimes,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,3,3,3
4,Albany,2012,Crimes Against Persons,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,5,5,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Westchester,2017,Property Crimes,0,0,0,0,0,1,2,...,0,0,0,0,0,0,0,16,16,16
601,Westchester,2018,Crimes Against Persons,0,0,0,0,0,1,2,...,2,0,0,0,0,0,0,6,6,6
602,Westchester,2018,Property Crimes,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,15,15,15
603,Westchester,2019,Crimes Against Persons,0,0,0,0,0,3,1,...,1,0,0,0,0,0,0,9,10,12
604,Westchester,2019,Property Crimes,0,0,0,0,0,0,2,...,0,1,0,0,0,0,0,14,14,14

In [5]:
austin = pd.read_csv("Resources/Austin_TX_Hate_Crimes_2020.csv")
austin.head()

,Month,Incident Number,Date of Incident,Day of Week,Number of Victims under 18,Number of Victims over 18,Number of Offenders under 18,Number of Offenders over 18,Race/Ethnicity of Offenders,Offense(s),Offense Location,Bias,Notes
0,March,2020-602085,3/1/2020,Sunday,0,1,0,1,White/Non-Hispanic,Criminal Mischief,Residence/Home,Anti-Black or African American,NaN
1,March,2020-680226,3/8/2020,Sunday,0,1,0,2,White/Hispanic,Assault,Parking Lot,Anti-Gay (Male); Anti-Transgender,NaN
2,March,2020-5011788,3/22/2020,Sunday,0,1,0,0,Unknown,Criminal Mischief,Residence/Home,Anti-Gay (Male); Anti-Jewish,NaN
3,April,2020-5015689,4/20/2020,Monday,0,1,0,0,Unknown,Criminal Mischief,Church/Synagogue/Temple/Mosque,Anti-Buddhist,NaN
4,April,2020-5016804,4/29/2020,Wednesday,0,1,0,1,Black/Non-Hispanic,Assault by Threat,Department/Discount Store,Anti-Gay (Male); Anti-Transgender,NaN

In [6]:
austin.shape

(35, 13)

In [12]:
hateCrimeBias['Agency Type'].value_counts()

Cities                       1325
Metropolitan Counties         217
Cities                        188
Nonmetropolitan Counties      148
Universities and Colleges      95
State Police Agencies          78
Federal Agencies               48
Other Agencies                 46
Metropolitan Counties          16
Nonmetropolitan Counties       11
State Police Agencies           1
Name: Agency Type, dtype: int64