In [21]:
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
hateCrimeBias = pd.read_csv("Hate_Crime_Incidents_per_Bias_Motivation_and_Quarter_by_State_Federal_and_Agency_2019.csv")
hateCrimeBias

,State,Agency Type,Agency,Race/\nEthnicity/\nAncestry,Religion,Sexual\norientation,Disability,Gender,Gender\nidentity,1st\nquarter,2nd\nquarter,3rd\nquarter,4th\nquarter,Population
0,Alaska,Cities,Anchorage,4.0,0,2.0,0.0,0.0,0.0,1.0,2.0,3.0,0.0,"287,731"
1,Alaska,Cities,Fairbanks,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"31,493"
2,Alaska,Cities,Kotzebue,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,"3,272"
3,Alaska,Cities,North Pole,1.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,"2,111"
4,Alaska,Cities,Soldotna,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,"4,756"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2170,Federal,Federal Agencies,Pentagon Force Protection Agency,0.0,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN
2171,Federal,Federal Agencies,U.S. Navy Law Enforcement,4.0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,NaN
2172,Federal,Federal Agencies,United States Army,0.0,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
nyc = pd.read_csv("Resources/New_York_Hate_Crimes_by_County_and_Bias_Type_2010-2019.csv")
nyc

,County,Year,Crime Type,Anti-Male,Anti-Female,Anti-Transgender,Anti-Gender Identity Expression,Anti-Age*,Anti-White,Anti-Black,...,Anti-Gay Male,Anti-Gay Female,Anti-Gay (Male and Female),Anti-Heterosexual,Anti-Bisexual,Anti-Physical Disability,Anti-Mental Disability,Total Incidents,Total Victims,Total Offenders
0,Albany,2010,Crimes Against Persons,0,0,0,0,0,0,9,...,2,1,0,0,0,0,0,13,13,20
1,Albany,2010,Property Crimes,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,2,2,2
2,Albany,2011,Crimes Against Persons,0,0,0,0,0,0,4,...,2,0,0,0,0,0,0,7,7,7
3,Albany,2011,Property Crimes,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,3,3,3
4,Albany,2012,Crimes Against Persons,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,5,5,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,Westchester,2017,Property Crimes,0,0,0,0,0,1,2,...,0,0,0,0,0,0,0,16,16,16
601,Westchester,2018,Crimes Against Persons,0,0,0,0,0,1,2,...,2,0,0,0,0,0,0,6,6,6
602,Westchester,2018,Property Crimes,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,15,15,15
603,Westchester,2019,Crimes Against Persons,0,0,0,0,0,3,1,...,1,0,0,0,0,0,0,9,10,12
604,Westchester,2019,Property Crimes,0,0,0,0,0,0,2,...,0,1,0,0,0,0,0,14,14,14